
# docker-compose scale service-db=3

services:

  service-db:
    image: postgres:13

    environment:
      POSTGRES_DB: amazin
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

    volumes:
      - ./Db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "8080"  # Internal container port
      - "5432:5432"  # Dynamically assign any available host port to container port 5432

    networks:
      - web


networks:
  web:
    driver: bridge
